# Generating of SSH Pair keys

# Resource: tls_private_key
#
## Generates a secure private key and encodes it as PEM. This resource is primarily intended 
# for easily bootstrapping throwaway development environments.
# The private key generated by this resource will be stored unencrypted in your Terraform 
# state file. Use of this resource for production deployments is NOT RECOMMENDED. 
# Instead, generate a private key file outside of Terraform and distribute it securely to 
# the system where Terraform will be run.
#
# https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key

//Creating Key
resource "tls_private_key" "tls_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}



# Resource: aws_key_pair
#
# Provides an EC2 key pair resource. A key pair is used to control login access to EC2 instances.
# Currently this resource requires an existing user-supplied key pair. This key pair's public 
# key will be registered with AWS to allow logging-in to EC2 instances.
# When importing an existing key pair the public key material may be in any format supported 
# by AWS. Supported formats (per the AWS documentation) are:
#   - OpenSSH public key format (the format in ~/.ssh/authorized_keys)
#   - Base64 encoded DER format
#   - SSH public key file format as specified in RFC4716
#
# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/key_pair

//Generating Key-Value Pair
resource "aws_key_pair" "generated_key" {
  key_name   = "eks-key"
  public_key = tls_private_key.tls_key.public_key_openssh

  depends_on = [
    tls_private_key.tls_key
  ]
}




# Resource: local_file
#
# Generates a local file with the given content.
# When working with local files, Terraform will detect the resource as having been deleted each 
# time a configuration is applied on a new machine where the file is not present and will generate 
# a diff to re-create it. This may cause "noise" in diffs in environments where configurations 
# are routinely applied by many different users or within automation systems.
#
# https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file

//Saving Private Key PEM File
resource "local_file" "key-file" {
  content_base64    = tls_private_key.tls_key.private_key_pem
  filename          = "eks-key.pem"

  depends_on = [
    tls_private_key.tls_key
  ]
}
