# Generating of SSH Pair keys

# Resource: tls_private_key
#
## Generates a secure private key and encodes it as PEM. This resource is primarily intended 
# for easily bootstrapping throwaway development environments.
# The private key generated by this resource will be stored unencrypted in your Terraform 
# state file. Use of this resource for production deployments is NOT RECOMMENDED. 
# Instead, generate a private key file outside of Terraform and distribute it securely to 
# the system where Terraform will be run.
#
# https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key

//Creating Key
resource "tls_private_key" "tls_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}
