# grafana-service
apiVersion: v1
kind: Service
metadata:
  namespace: grafana
  name: grafana-srv
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 30600
