/*
    THIS FILE INTENDED FOR JOOMLA WEB-SERVER DOCKER IMAGE BUILD AND PUSHING IT IN DOCKER HUB REGISTRY
 */
pipeline {
    agent any

    environment {
      J_DKR_IMG_NM="fomindn/joomla:4.0.5"
      M_DKR_IMG_NM="fomindn/mysql:5.7.36"
      P_DKR_IMG_NM="fomindn/pma:5.1.1"
    }

    stages {
        // Stage #1 - Build docker images with Dockerfiles help
        stage('Build') {
            environment {
                JENK=credentials('Jenkins-user')
            }
            steps {
                dir("Fomin_Dmytro/02.Jenkins/joomla-webs/") {
                    //Building Docker image with Joomla
                    sh "docker build -f Dockerfiles/Dockerfile.joomla -t ${env.J_DKR_IMG_NM} ."

                    //Building Docker image with MySQL
                    sh "docker build -f Dockerfiles/Dockerfile.mysql -t ${env.M_DKR_IMG_NM} ."

                    //Building Docker image with phpMyAdmin
                    sh "docker build -f Dockerfiles/Dockerfile.pma -t ${env.P_DKR_IMG_NM} ."
                }
            }
        }
        // Stage #2 - Test builded docker image 
        stage('Test') {
            steps {
                echo "Here can be implemented different Docker images tests."
            }
        }
        
        // Stage #3 - Push docker images to the registry Docker Hub
        stage('Push'){
            environment {
                DHUB=credentials('DockerHub-token')
            }
            steps{
                // Login to Docker Hub
                sh 'docker login -u $DHUB_USR -p $DHUB_PSW'

                // Push images to the registry Docekr Hub
                sh "docker push ${env.J_DKR_IMG_NM}"
                sh "docker push ${env.M_DKR_IMG_NM}"
                sh "docker push ${env.P_DKR_IMG_NM}"
            }
        }

        // Stage #4 - Deploy docker image
        stage('Deploy') {
            steps {
                sh 'docker stop joomla mysql-db pma || true'
                sh 'docker rm joomla mysql-db pma || true'
                sh 'docker network create mysql-net || true'
                withCredentials([file(credentialsId: 'mysql.env', variable: 'MYSQL_ENV')]) {
                    // Start MySQL docker file
                  sh "docker run -tid --rm --name mysql-db -h mysql-db -p 3306:3306 --net mysql-net -v  webs-mysql-db:/var/lib/mysql \
                      -e MYSQL_DATABASE=joomla-db --env-file=\$MYSQL_ENV ${env.M_DKR_IMG_NM}"
                }
                  
                withCredentials([file(credentialsId: 'pma.env', variable: 'PMA_ENV')]) {
                  // Start PMA docker file
                  sh "docker run -tid --rm --name pma -h pma -p 85:80 --net mysql-net --env-file=\$PMA_ENV -e PMA_HOST=mysql-db \
                      ${env.P_DKR_IMG_NM}"
                }

                withCredentials([file(credentialsId: 'joomla.env', variable: 'JOOMLA_ENV')]) {
                  // Start Joomla docker file
                  sh "docker run -tid --rm --name joomla -h joomla -p 80:80 --net mysql-net -v webs-joomla-scode:/var/www/html \
                      -e JOOMLA_DB_HOST=mysql-db --env-file=\$JOOMLA_ENV ${env.J_DKR_IMG_NM}"
                }
            }
        }

    }
    post {
        always {
            sh 'docker logout'
        }
    }
}
