/*
    THIS FILE INTENDED FOR JOOMLA WEB-SERVER DOCKER IMAGE BUILD AND PUSHING IT IN DOCKER HUB REGISTRY
 */
pipeline {
    agent any

    environment {
      J_DKR_IMG_NM="fomindn/joomla:4.0.5"
      M_DKR_IMG_NM="fomindn/mysql:5.7.36"
      P_DKR_IMG_NM="fomindn/pma:5.1.1"
    }

    stages {
        // Stage #1 - Build docker images with Dockerfiles help
        stage('Build') {
            environment {
                JENK=credentials('Jenkins-user')
            }
            steps {
                dir("Fomin_Dmytro/02.Jenkins/joomla-webs/") {
                    //Building Docker image with Joomla
                    sh "docker build -f Dockerfiles/Dockerfile.joomla -t ${env.J_DKR_IMG_NM} ."

                    //Building Docker image with MySQL
                    sh "docker build -f Dockerfiles/Dockerfile.mysql -t ${env.M_DKR_IMG_NM} ."

                    //Building Docker image with phpMyAdmin
                    sh "docker build -f Dockerfiles/Dockerfile.pma -t ${env.P_DKR_IMG_NM} ."
                }
            }
        }
        // Stage #2 - Test builded docker image 
        stage('Test') {
            steps {
                echo "Here can be implemented different Docker images tests."
            }
        }
        
        // Stage #3 - Push docker images to the registry Docker Hub
        stage('Push'){
            environment {
                DHUB=credentials('DockerHub-token')
            }
            steps{
                // Login to Docker Hub
                sh 'docker login -u $DHUB_USR -p $DHUB_PSW'

                // Push images to the registry Docekr Hub
                sh "docker push ${env.J_DKR_IMG_NM}"
                sh "docker push ${env.M_DKR_IMG_NM}"
                sh "docker push ${env.P_DKR_IMG_NM}"
            }
        }

        // Stage #4 - Deploy docker image
        stage('Deploy') {
            steps {
                sh 'docker stop joomla mysql-db pma || true'
                sh 'docker rm joomla mysql-db pma || true'
                sh 'docker network create mysql-net || true'
                dir("Fomin_Dmytro/02.Jenkins/joomla-webs/") {
                  sh './joomla-docker.sh 1'
                }
            }
        }

    }
    post {
        always {
            sh 'docker logout'
        }
    }
}
